apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-dns
spec:
  template:
    spec:
      containers:
        - name: quarkus-dns
          env:
            - name: TEST
              value: "TEST"