greeting:
  message: "hello"
quarkus:
  kubernetes-client:
    api-server-url: https://lab.cch.com:6500
  container-image:
    group: cch0124
    name: ${quarkus.application.name:unset}
    tag: ${quarkus.application.version:latest}
    builder: jib
    labels:
      "maintainer": cch
      "app": ${quarkus.application.name}
    registry: registry.hub.docker.com
  jib:
    base-native-image: quay.io/quarkus/quarkus-micro-image:2.0
    # user: itachi
    working-directory: /home/jboss
    
  kubernetes:
    deployment-kind: Deployment
    replicas: 1
    strategy: rolling-update
    service-type: cluster-ip
    prometheus:
      annotations: true
      generate-service-monitor: true
    namespace: default
    resources:
      requests:
        memory: 128Mi
        cpu: 10m
      limits:
        memory: 256Mi
        cpu: 100m
    ingress:
      expose: false
    service-account: ${quarkus.application.name}
    rbac:
      cluster-roles:
        app-role:
          name: "app-role"
          policy-rules:
            "0":
              - api-groups:
                - ""
                resources:
                  - nodes
                verbs:
                  - list
              - api-groups: 
                  - "events.k8s.io"
                resources: 
                  - "events"
                verbs: 
                  - "create"
      cluster-role-bindings:
        app-role-binding:
          name: "app-role-binding"
          role-name: "app-role"
          subjects:
            helm-kz-example:
              name: ${quarkus.applicatioen.name}
              kind: ServiceAccount
              namespace: ${namespace}
    output-directory: kubernetes
    