quarkus:
  application:
    version: ${git.tag}
  container-image:
    group: cch0124
    name: ${quarkus.application.name:unset}
    tag: ${quarkus.application.version:latest}
    builder: jib
    labels:
      "maintainer": cch
      "app": ${quarkus.application.name}
    registry: registry.hub.docker.com
  jib:
    base-native-image: quay.io/quarkus/quarkus-micro-image:2.0
    working-directory: /home/jboss