apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-dns
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/version: day16
      app.kubernetes.io/name: quarkus-dns
  template:
    spec:
      serviceAccountName: quarkus-dns
      securityContext:
        fsGroup: 2000
      containers:
        - name: quarkus-dns
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: "registry.hub.docker.com/cch0124/quarkus-dns:day16"
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBE_POD_NAME 
              valueFrom: 
                fieldRef: 
                  fieldPath: metadata.name
            - name: QUARKUS_CONFIG_LOCATIONS
              value: /opt/config/application.yaml
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: vertx-cache
              mountPath: /tmp/vertx-cache
            - name: config-volume
              mountPath: /home/jboss/config
              readOnly: true
      volumes:
        - name: vertx-cache
          emptyDir: {}
        - name: config-volume
          configMap:
            name: quarkus-dns-config
