apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- serviceaccount.yaml
namespace: day19
buildMetadata:
- managedByLabel
commonAnnotations:
  app.quarkus.io/createded-by: quarkus
  app.quarkus.io/quarkus-version: 3.14.2
images:
- name: registry.hub.docker.com/cch0124/helmchartlab
  newName: registry.hub.docker.com/cch0124/helmchartlab
  newTag: day19
namePrefix: cch-
replicas:
- count: 5
  name: quarkus-dns
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: quarkus-dns
    app.kubernetes.io/version: day16
