apiVersion: v1
kind: Service
metadata:
  name: test-quarkus-dns
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: quarkus-dns
    app.kubernetes.io/version: day16
