quarkus:
  container-image:
    group: cch0124
    name: ${quarkus.application.name:unset}
    tag: ${quarkus.application.version:latest}
    builder: jib
    labels:
      "maintainer": cch
      "app": ${quarkus.application.name}
    registry: registry.hub.docker.com
  jib:
    platforms: linux/amd64