{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus-dns.fullname" . }}-config
  labels:
    {{- include "quarkus-dns.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  application.yaml: |- 
    {{- include "quarkus-dns.applicationTemplate" . | nindent 2 }}
{{- end }}
